### ISSUE TITLE
High and low SOC target not shown as configured

### ISSUE THREAD

**Issue by MarcWeickenmeier** [weltenwort/home-assistant-rct-power-integration#329]
## Version of the custom_component

v0.10.0

## Describe the bug

SOC min target is set to 0,20.
SOC high target is set to 0,97.

sensor.rct_power_storage_battery_state_of_charge_high_target has the value 1,0.
sensor.rct_power_storage_battery_state_of_charge_low_target has also the value 1,0.

What am I doing wrong?

```

**Comment by weltenwort** [comment]
Hi @MarcWeickenmeier :wave: I'm actually observing the same, so it's not any fault of yours. These values returned by the inverter don't seem to mean what your description implies. Unfortunately there is no good official documentation of the semantics.

There are other registers called `power_mng.soc_min_island` and `power_mng.soc_max` that *might* have the meaning that you're looking for. I'll give it a try and see what happens if I read them.
